const https = require("https");

function fetchText(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      let data = "";
      res.on("data", (c) => (data += c));
      res.on("end", () => resolve({ status: res.statusCode, body: data }));
    }).on("error", reject);
  });
}

function extractTitles(html) {
  const out = [];
  const candidates = [];
  const re = /<h[1-3][^>]*>([\s\S]*?)<\/h[1-3]>/g;
  let m = null;
  while ((m = re.exec(html)) !== null) {
    const raw = (m[1] || "").replace(/<[^>]+>/g, "").trim();
    if (raw && raw.length >= 10 && raw.length <= 140) candidates.push(raw);
    if (candidates.length >= 30) break;
  }
  for (const t of candidates) {
    if (!out.includes(t)) out.push(t);
    if (out.length >= 12) break;
  }
  return out;
}

async function main() {
  const url = process.argv[2] || "https://newsclip.com/terms/";
  const res = await fetchText(url);

  const titles = extractTitles(res.body || "");
  const lines = [];
  lines.push("# Digest");
  lines.push("");
  lines.push("Source: " + url);
  lines.push("");
  for (const t of titles) {
    lines.push("- " + t);
  }
  lines.push("");
  lines.push("Generated by newsclip-terms-policy-watcher");

  console.log(lines.join("\n"));
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
